### ISSUE TITLE
env export vs export env

### ISSUE THREAD

**Issue by ajanders** [patrickmineault/codebook#1]
On the website, when exporting your Python environment, you list the command as:

`conda export env > environment.yml`

 This didn't work for me, and the [Conda webpage](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html) says to use:

 `conda env export > environment.yml`

This worked for me.

**Comment by patrickmineault** [comment]
Fixed here https://github.com/patrickmineault/codebook/commit/3601bc37b3c709d023bc16a764e7ef6bf934a3c3
