### ISSUE TITLE
PDF version

### ISSUE THREAD

**Issue by Tobias-Fischer** [patrickmineault/codebook#10]
Hiya,

I really love the codebook! It would be nice to have a PDF version. It seems jupyter-book allows you to do this: https://jupyterbook.org/advanced/pdf.html

**Comment by patrickmineault** [comment]
Thanks for the issue, I do have a pdf edition I've created - I will update the homepage and link to it.

**Comment by patrickmineault** [comment]
Resolved in https://github.com/patrickmineault/codebook/commit/aac427dff40c0511c053b5ec86b619f1e7d8d1e4
