### ISSUE TITLE
Talk about the difference genericizing conda environment.yml and pip freeze

### ISSUE THREAD

**Issue by patrickmineault** [patrickmineault/codebook#16]
Oftentimes, the environment you get through exporting environment.yml or pip freeze is too specific; it doesn't work on other systems. Write about alternative ways of freezing the environment that are more flexible.

e.g. https://github.com/patrickmineault/codebook/issues/15

**Comment by mireille-raad** [comment]
If you are no longer changing the packages, would it be useful to provide both ` environment.yml ` and `requirements.txt` files?

If someone is using `pip` or `conda`, they can choose what they can run.

If the packages might change, it will be a hassle for you to maintain both files...

**Comment by patrickmineault** [comment]
Whether it's through environment.yml or requirements.txt, the consequences are similar: `pip freeze` and `conda export` document OS-specific packages that aren't portable.

Resolved by https://github.com/patrickmineault/codebook/commit/bf432d7b6322beab1703c569d79113a06b026f42. I write about automatic export through `conda`, and how it will create reproducible but not portable environments, and how to solve that by writing environment.yml files manually.
