### ISSUE TITLE
command to recover environment from yml file did not work

### ISSUE THREAD

**Issue by nicoa47** [patrickmineault/codebook#18]
`conda create --name recoveredenv --file environment.yml`
did not work, but instead:
`conda env create --name recoveredenv --file environment.yml`

This might need to be changed in the handbook.

Thanks!

**Comment by patrickmineault** [comment]
Fixed here https://github.com/patrickmineault/codebook/commit/49885c83f054f7af896c345b36f75ae8327ffe70

**Comment by psarahdactyl** [comment]
when downloading from [here](https://zenodo.org/record/5796873), I still had this problem

**Comment by patrickmineault** [comment]
I'll package that with the next release
