### ISSUE TITLE
Small typo in setup.html

### ISSUE THREAD

**Issue by rorybyrne** [patrickmineault/codebook#3]
Howdy, it looks like there's a typo in `__init__.py__` [here](https://goodresearch.dev/setup.html#create-a-init-py-file), with an unexpected `__` at the end!

Also great work on the guide, really enjoying it so far!

**Comment by patrickmineault** [comment]
Thanks for reporting! Fixed by https://github.com/patrickmineault/codebook/commit/00827be6e542246eb61e4e2c2428b1c3478fa183
