### ISSUE TITLE
Tag not hidden from code

### ISSUE THREAD

**Issue by manuelhaussmann** [patrickmineault/codebook#8]
In the testing chapter, one of the code cells has some tags that should probably be hidden in the rendered version so to not cause any confusion for the reader.
The problematic cell is this one:
https://github.com/patrickmineault/codebook/blob/f4cc9b7371dea93a250b8efdc4db37ed1cbb9840/testing.md?plain=1#L100

Thanks for a really nice book!

**Comment by patrickmineault** [comment]
Thanks, resolved by https://github.com/patrickmineault/codebook/commit/62c676c4e5646df2a6d8d2a04a13e33ce7232450
